<?php

/**
 * Implements hook_theme().
 */
function solych_theme($existing, $type, $theme, $path) {
  $template_path = \Drupal::service('extension.path.resolver')->getPath('module', 'solych') . '/templates';

  return [
    'cats-page' => [
      'variables' => [
        'markup' => NULL,
        'title' => NULL,
        'cats_form' => NULL,
      ],
      'template' => 'cats-page',
      'path' => $template_path,
    ]
  ];
}
